### ISSUE TITLE
import main

### ISSUE THREAD

**Issue by AidenWard13** [zzh8829/PythonCraft#1]
Traceback (most recent call last):
  File "C:\Users\Aiden\Desktop\PythonCraft-master\PythonCraft.py", line 5, in <module>
    import main
ImportError: DLL load failed: The specified module could not be found.

what version python you need?

**Comment by zzh8829** [comment]
You need to compile the c++ module see level/cmakelist.txt you will need boost Python and sdl library
I believe the compiled version in repo is for Python3.2 on windows

**Comment by AidenWard13** [comment]
can you point me in the right direction please? i've never used boost before.

**Comment by Fliu777** [comment]
He fixed it!

**Comment by zzh8829** [comment]
See the updated readme file on how to build on Mac with Python 3
Windows is currently not supported will add in future
